# https://travis-ci.org/#!/phlax/elastic

env:
  jobs:
    - BEATS_BRANCH=7.x

install:
  - make images

script:
  - docker images

before_deploy:
  - echo $DOCKER_API_TOKEN | docker login -u phlax --password-stdin

deploy:
  provider: script
  script: make hub-images
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
