apm-server:
  host: "0.0.0.0:8200"
  rum.enable: true
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: '${ELASTICSEARCH_USERNAME:elastic}'
  password: '${ELASTICSEARCH_PASSWORD:}'
http:
  enabled: true
  host: unix:///var/run/sockets/status/apm-server.sock
monitoring.enabled: false
